# Generated by Django 4.2 on 2023-12-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('color', models.IntegerField(choices=[(1, 'Green'), (2, 'Red')])),
                ('compare', models.BooleanField(blank=True, default=False, null=True)),
                ('conditional', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies_candles', to='strategy.strategy')),
            ],
            options={
                'verbose_name': 'Strategy Candle',
                'verbose_name_plural': 'Strategies Candles',
                'db_table': 'strategy_candle',
            },
        ),
    ]
