# Generated by Django 4.2 on 2023-12-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1, null=True)),
            ],
            options={
                'verbose_name': 'Active',
                'verbose_name_plural': 'Active',
                'db_table': 'active',
            },
        ),
    ]
