# Generated by Django 4.2 on 2023-12-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1, null=True),
        ),
        migrations.RemoveField(
            model_name='broker',
            name='active',
        ),
        migrations.AddField(
            model_name='broker',
            name='active',
            field=models.ManyToManyField(blank=True, related_name='brokers', to='active.active'),
        ),
    ]
