# Generated by Django 4.2 on 2023-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1, null=True)),
                ('cycles', models.ManyToManyField(blank=True, related_name='strategies', to='cycle.cycle')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategy',
            },
        ),
    ]
