# Generated by Django 4.2 on 2023-12-24 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identity_broker', models.IntegerField()),
                ('date_from', models.IntegerField()),
                ('date_at', models.IntegerField()),
                ('date_to', models.IntegerField()),
                ('value_open', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('value_close', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('value_max', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('value_min', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1, null=True)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='active.active')),
            ],
            options={
                'verbose_name': 'Candle',
                'verbose_name_plural': 'Candles',
                'db_table': 'candle',
            },
        ),
    ]
