# Generated by Django 4.2 on 2023-12-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soros', '0001_initial'),
        ('martingale', '0002_martingale_reverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1, null=True)),
                ('martingale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='martingale.martingale')),
                ('soros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='soros.soros')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycle',
                'db_table': 'cycle',
            },
        ),
    ]
